### ISSUE TITLE
group resource display stops working

### ISSUE THREAD

**Issue by untropy** [simp/puppet-gpasswd#2]
Hi there,

I want to try using your gpasswd module, but it seems to break the command 'puppet resource gorup <groupname>', which I need to work in my environment. I'm using pe-puppet-3.7.3.3-1.pe.el6.noarch

Any chance this can be fixed?

Output:
# grep labr_prd /etc/group

labr_prd:!:236:labr_prd
# puppet resource group labr_prd

Error: Could not run: undefined method `-' for nil:NilClass

**Comment by trevor-vaughan** [comment]
Hi, I apologize for this, I don't know that I've tried it in that particular scenario.

Let me take a look and see what I can do. This _may_ be the classloader ordering issue in puppet rearing its head.

**Comment by trevor-vaughan** [comment]
This should be fixed, let me know if you have any other issues with the module!

**Comment by untropy** [comment]
I'll check it out, thanks!

**Comment by untropy** [comment]
Works perfectly for me, thank you again! This is going to make my life much easier.
