### ISSUE TITLE
Lack of spaces in the noop message between user names

### ISSUE THREAD

**Issue by usmanismail** [simp/puppet-gpasswd#3]
Notice: /Stage[main]/User::Jenkins/Group[xxx-xxxx]/members: current_value jenkinsuismail, should be jenkinsmanagehometrueensurepresent (noop)

**Comment by trevor-vaughan** [comment]
Thanks for the report! We'll get this patched.

**Comment by trevor-vaughan** [comment]
Hi @usmanismail,

Could you please provide the version of Puppet and Ruby you're running this against?

Thanks

**Comment by usmanismail** [comment]
Thanks, The versions are below.

puppet --version
3.7.3

ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

**Comment by trevor-vaughan** [comment]
It looks like I just need to implement the 'members_to_s' method, but I need to validate this on a live system.
