### ISSUE TITLE
members list order changes cause "members changed" notice on each run

### ISSUE THREAD

**Issue by sknolin** [simp/puppet-gpasswd#4]
If I create a members list and change the order in hiera, every puppet run will send a notice.

For example, with a group called "example_group"

Heira:

```
groups::example_group:
  - user1
  - user2
```

Reverse the order of those and I get this every run:

```
Notice: /Stage[main]/Groups/Groups::System/Group[example_group]/members: members changed 'user1,user2' to 'user2,user1'
```

Similarly, if you insert a "-user3" at the top of the list, you get a notice every time.

To be clear, the group has the correct membership, it's just that gpasswd simply does it's thing and doesn't care about order.

Scott

**Comment by sknolin** [comment]
puppet-3.8.1-1.el6
hiera-1.3.4-1

I have a feeling versions don't matter here, but there they are.

**Comment by trevor-vaughan** [comment]
Thanks for the feedback. I'll take a look at this as soon as I can.

**Comment by sknolin** [comment]
Looking around a bit, the group type used for OS X, which does support group membership via directory service has this very same problem:

https://projects.puppetlabs.com/issues/4835
https://tickets.puppetlabs.com/browse/PUP-2575

5 years and no real fix is pretty depressing to see there. But so is the fact that this isn't in the puppet native group type for linux anyhow. Ridiculous.

Anyway, all this bug boils down to is not comparing sorted lists.

The tickets above reference refactoring the members property to 'properties::orderedlist'

Scott

**Comment by oskar023** [comment]
A ".sort" in the end of line 47 and a sorted member list in the Puppet resource definition (or Hiera) seem to work around the issue for me.

**Comment by deric** [comment]
I'm having the same issue, any chance to fix this?

**Comment by trevor-vaughan** [comment]
I'm looking at this but it may be an issue with the underlying group resource. Will continue to figure this out.

**Comment by jessestroik** [comment]
I tested a solution that seems to work, but it requires you to change both the provided gpasswd.rb and your implementation in puppet. In group/gpasswd.rb, change the return value to a sorted array:

`def members`

```
retval = @objectinfo.mem
if @resource[:members] and
   ( @resource[:attribute_membership] == :minimum ) and
   (@resource[:members] - @objectinfo.mem).empty?
then
    retval = @resource[:members]
end
retval.sort
```

`end`

In your code:

`group { 'groupname':
  attribute_membership => inclusive,
  members               => $memberlist,
}`

Just be sure that your memberlist is sorted. For example:

`$memberlist = sort(hiera('groups::groupname'))`
