### ISSUE TITLE
MIN/MAX-Values for GID not honored

### ISSUE THREAD

**Issue by ghost** [simp/puppet-gpasswd#7]
The module does respect the values from login.defs (at least on RHEL Systems)

/etc/login.defs:
```
(...)
SYS_GID_MIN	201
SYS_UID_MIN	201
SYS_GID_MAX	499
SYS_UID_MAX	499
```
My Group-Ressource:

```
group { 'testgroup':
        ensure          => present,
        name            => 'testgroup',
         system          => true,                                                                                                                                                                          
         auth_membership => true,
        members         => ['user1', 'user2']
} 
```

Result:
```
# getent group pc
testgroup:x:992:user1,user2
```
Expected result:
GID in range between 201 and 499

**Comment by trevor-vaughan** [comment]
@domfi If you remove the `members` array, does it work properly? I think this might be a bug in the main `groupadd` provider since `gpasswd` inherits the `addcmd` method from that.

**Comment by ghost** [comment]
The same behaviour without "members" array.

It seems that the default "provider" is not "groupadd". If I add
```
provider => 'groupadd'
```
to my resource, the GID is within the correct range.

**Comment by trevor-vaughan** [comment]
Hmm....strange. Can you see if everything works as expected when you set `members` as well as `provider => 'groupadd'`.

If that does not work (it shouldn't add the additional members to your group) then can you try it with `provider => 'gpasswd'`?

That should add the members to the group.

**Comment by ghost** [comment]
Here's an update of my observations so far:


Configuration with `groupadd` provider:
```
group { 'testgroup':
        ensure          => present,
        name            => 'testgroup',
        system          => true,
        auth_membership => true,
        provider        => 'groupadd',
        members         => ['user1', 'user2']
} 
```

results in correct GID (within range from /etc/login.defs), but no members are included:

```
# getent group testgroup
testgroup:x:496:
```

---

Configuration without provider set:
```
group { 'testgroup':
        ensure          => present,
        name            => 'testgroup',
        system          => true,
        auth_membership => true,
        members         => ['user1', 'user2']
} 
```

results in wrong GID (not within defined range from /etc/login.defs) but members included:

```
# getent group testgroup
testgroup:x:995:user1,user2
```

---

Configuration with `gpasswd` provider set:
```
group { 'testgroup':
        ensure          => present,
        name            => 'testgroup',
        system          => true,
        auth_membership => true,
        provider        => 'gpasswd',
        members         => ['user1', 'user2']
} 
```

results in wrong GID:
```
# getent group testgroup
testgroup:x:995:user1,user2
```

**Comment by nick-markowski** [comment]
@domfi you can track progress on this issue here https://simp-project.atlassian.net/browse/SIMP-4085. Thanks again for the feedback!

**Comment by trevor-vaughan** [comment]
@domfi Could you check the fix in #8 and see if if resolves your issue?

**Comment by ghost** [comment]
@trevor-vaughan, @nick-markowski : I've checked it and it resolves my issue. Thank you!

**Comment by nick-markowski** [comment]
@domfi Glad to help! We'll get this merged and released asap.
